trigger:
  - main

variables:
  pythonVersion: '3.12'
  artifactName: 'drop'
  appServiceName: 'appservice-javi'
  # PUBLISH_PROFILE should be set as a pipeline secret variable

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test'
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

          - task: MicrosoftSecurityDevOps@1
            displayName: 'Initialize CodeQL'
            inputs:
              languages: 'python'
              buildtype: 'none'

          - task: MicrosoftSecurityDevOps@1
            displayName: 'Perform CodeQL Analysis'

          - script: |
              mkdir -p $(Build.ArtifactStagingDirectory)
            displayName: 'Ensure artifact staging directory exists'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(pythonVersion).zip'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: '$(artifactName)'
              publishLocation: 'Container'

          - script: |
              pip install pytest pytest-azurepipelines
              pytest
            displayName: 'Run pytest'

  - stage: DeployProduction
    displayName: 'Deploy to Production'
    dependsOn: BuildAndTest
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: 'Deploy with Publish Profile'
        pool:
          vmImage: ubuntu-latest
        steps:
          - download: current
            artifact: $(artifactName)

          - script: |
              echo "Listing contents of artifact"
              ls -lh $(Pipeline.Workspace)/$(artifactName)
            displayName: 'List downloaded artifact contents'

          - task: Bash@3
            displayName: 'Deploy to Azure App Service using publish profile'
            env:
              PUBLISH_PROFILE: $(PUBLISH_PROFILE) # This should be set as a pipeline secret variable
            inputs:
              targetType: 'inline'
              script: |
                # Save the publish profile to a file
                echo "$PUBLISH_PROFILE" > publish-profile.xml

                # Extract userName and userPWD from publish profile XML
                userName=$(xmllint --xpath "string(//publishProfile[@publishMethod='MSDeploy']/@userName)" publish-profile.xml)
                userPWD=$(xmllint --xpath "string(//publishProfile[@publishMethod='MSDeploy']/@userPWD)" publish-profile.xml)

                # The publish URL for zipdeploy
                ZIPDEPLOY_URL="https://$(appServiceName).scm.azurewebsites.net/api/zipdeploy"

                # Find the zip artifact
                ZIP_FILE=$(find $(Pipeline.Workspace)/$(artifactName) -type f -name "*.zip" | head -n 1)

                # Deploy using curl
                echo "Deploying $ZIP_FILE to $ZIPDEPLOY_URL"
                curl -X POST "$ZIPDEPLOY_URL" \
                  --user "$userName:$userPWD" \
                  --data-binary @"$ZIP_FILE"

                # Optional: Print response
                echo "Deployment complete"
